### ISSUE TITLE
"api-resources" command doesn't work well

### ISSUE THREAD

**Issue by paugay** [tjamet/kubectl-switch#1]
For Kubernetes 1.6:

Using `kubectl-switch` for the `api-resources` command doesn't seem to work well:
```
$ k api-resources
Error: unknown command "api-resources" for "kubectl"
Run 'kubectl --help' for usage.
```

Where as directly going with `kubectl` works fine:
```
$ kubectl api-resources
NAME                         SHORTNAMES   APIGROUP                    NAMESPACED   KIND
bindings                                                              true         Binding
componentstatuses            cs                                       false        ComponentStatus
configmaps                   cm                                       true         ConfigMap
[...]
```

**Comment by tjamet** [comment]
thanks for reporting @paugay 
I will investigate

**Comment by tjamet** [comment]
can you confirm me the versions of your kubectl and cluster please? (the output of `k version`)

**Comment by paugay** [comment]
Sure!

```
$ k version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.13", GitCommit:"14ea65f53cdae4a5657cf38cfc8d7349b75b5512", GitTreeState:"clean", BuildDate:"2017-11-22T20:29:21Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.13+coreos.0", GitCommit:"d38c047b64709db853a76ed73d00fe3e02967bf6", GitTreeState:"clean", BuildDate:"2017-11-29T11:17:38Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tjamet** [comment]
Hi, 
sorry about the delay.
I have checked, there is no `api-resources` command in `kubectl` before v1.11.0 added by this commit https://github.com/kubernetes/kubernetes/commit/110641b34c9e220171f319af6e4f48464cc7a3d6#diff-9fbd69febdc1959afbf2a2ebceebf9b0

**Comment by tjamet** [comment]
Hi! Given api-resources has been added later than 1.6 and that this project aims at providing the exact kubectl version the server runs but does not aim (yet?) at providing backward compatibility, I would close this issue.
